version: '3.4'

services:
  ytsharing:
    image: ytsharing
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    env_file: .env
    restart: unless-stopped
    ports:
      - 5173:5173
